### ISSUE TITLE
请问，能提供这个文件吗

### ISSUE THREAD

**Issue by 501956430** [flypan/loadWeexProjectImage#1]
import image from './config';

**Comment by SeongBrave** [comment]
有同样的错误啊，怎么搞啊？？

**Comment by flypan** [comment]
啊，不好意思。当时忘上传了，就直接创建一个config.js，把我文章中的那一段拷贝过去就OK了

**Comment by 501956430** [comment]
@flypan  ? 为什么文章

**Comment by flypan** [comment]
http://www.jianshu.com/p/35f63f7bd2f4

拷贝：
const SERVER = "YOUR SERVER IP";
module.exports = {
    // 加载工程中的image
    loadImage(imgName) {
        var image = require('./resources/'+imgName);
        return image;
    },
    // 加载服务器上的image
    image(imgURL) {
        return SERVER + imgURL;
    }
}
